Models/ErrorViewModel.cs
using System;

namespace TestTaskEducationERP.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/NewMovieVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestTaskEducationERP.Models
{
    public class NewMovieVm
    {
        public string Name { get; set; }
        public string Desc { get; set; }
        public string Producer { get; set; }
        public int? Year { get; set; }
    }
}

Areas/Identity/Pages/Account/RegisterConfirmation.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace TestTaskEducationERP.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class RegisterConfirmationModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _sender;

        public RegisterConfirmationModel(UserManager<IdentityUser> userManager, IEmailSender sender)
        {
            _userManager = userManager;
            _sender = sender;
        }

        public string Email { get; set; }

        public bool DisplayConfirmAccountLink { get; set; }

        public string EmailConfirmationUrl { get; set; }

        public async Task<IActionResult> OnGetAsync(string email, string returnUrl = null)
        {
            if (email == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByEmailAsync(email);
            if (user == null)
            {
                return NotFound($"Unable to load user with email '{email}'.");
            }

            Email = email;
            // Once you add a real email sender, you should remove this code that lets you confirm the account
            DisplayConfirmAccountLink = true;
            if (DisplayConfirmAccountLink)
            {
                var userId = await _userManager.GetUserIdAsync(user);
                var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                EmailConfirmationUrl = Url.Page(
                    "/Account/ConfirmEmail",
                    pageHandler: null,
                    values: new { area = "Identity", userId = userId, code = code, returnUrl = returnUrl },
                    protocol: Request.Scheme);
            }

            return Page();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestTaskEducationERP.Data;
using TestTaskEducationERP.Models;

namespace TestTaskEducationERP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using TestTaskEducationERP.Data;
using TestTaskEducationERP.Models;

namespace TestTaskEducationERP.Controllers
{
    public class MovieController : Controller
    {
        private readonly ApplicationDbContext _repository;
        private readonly IWebHostEnvironment _appEnvironment;
        public MovieController(ApplicationDbContext context, IWebHostEnvironment appEnvironment)
        {
            _repository = context;
            _appEnvironment = appEnvironment;
        }

        [HttpGet]
        public IActionResult Index(int id)
        {
            var model = _repository.AspNetMoviesTest.FirstOrDefault(a => a.Id == id);
            return View(model);
        }

        [Authorize]
        public IActionResult AddMovie()
        {
            return View();
        }

        [Authorize]
        public IActionResult EditMovie(int id)
        {
            var model = _repository.AspNetMoviesTest.FirstOrDefault(a => a.Id == id);
            return View(model);
        }

        [HttpGet]
        public JsonResult GetMovies(int page)
        {
            int count = 10;

            var list = _repository.AspNetMoviesTest.Skip(count * (page - 1)).Take(count)
                .Select(a => new { Id = a.Id, Name = a.Name, Year = a.Year }).ToList();
            
            var pages = Math.Ceiling((_repository.AspNetMoviesTest.Count() / 10.0));

            return Json(new { 
                List = list,
                Pages = pages
            });
        }

        [Authorize]
        [HttpPost]
        public async Task<JsonResult> AddMovie([FromBody]NewMovieVm model)
        {
            var movie = new Movie();
            movie.Name = model.Name;
            movie.Desc = model.Desc;
            movie.Producer = model.Producer;
            movie.Year = model.Year;
            movie.User = User.Identity.Name;

            _repository.AspNetMoviesTest.Add(movie);
            await _repository.SaveChangesAsync();

            string url = "/Movie/EditMovie/" + movie.Id;
            return Json(url);

        }

        [Authorize]
        [HttpPost]
        public async Task<JsonResult> SaveMovie([FromBody]Movie model)
        {
            _repository.AspNetMoviesTest.Update(model);
            await _repository.SaveChangesAsync();

            string url = "/Movie/Index/" + model.Id;
            return Json(url);
        }

        [HttpPost]
        public async Task<JsonResult> AddFile(IFormCollection uploadedFile)
        {
            string error = null;
            try
            {
                if (uploadedFile != null)
                {
                    var MovieId = JsonSerializer.Deserialize<int>(uploadedFile.First().Value);
                    var File = uploadedFile.Files.First();
                    string extension = Path.GetExtension(File.FileName);

                    string path = "/Files/" + Guid.NewGuid() + extension;
                    
                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.Files.First().CopyToAsync(fileStream);
                    }
                    var movie = _repository.AspNetMoviesTest.FirstOrDefault(a => a.Id == MovieId);
                    movie.PosterUrl = path;
                    _repository.AspNetMoviesTest.Update(movie);
                    await _repository.SaveChangesAsync();
                }
            }
            catch (Exception e)
            {
                error = e.Message;
            }

            return Json(error);
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div ng-app="myApp" ng-cloak ng-controller="myCtrl">

    @if (User.Identity.IsAuthenticated)
    {
        <div class="d-flex">
            <a style="margin-left: auto; max-height: 38px;"
                        class="btn btn-primary"
                        asp-area="" asp-controller="Movie" asp-action="AddMovie">
                    Add
                </a>
        </div>
    }

    <div style="min-height: 650px; margin-top: 10px" class="list-group">

        <a 
           href='Movie/Index/{{Item.id}}'
           class="list-group-item list-group-item-action flex-column align-items-start" 
           ng-repeat="Item in List">
            <div class="d-flex">
                <img style="max-height: 40px" src="~/movie_icon.png" />
                <h5 style="margin-left: 20px">{{Item.name}}</h5>
                <small style="margin-left: auto;">{{Item.year}} year</small>
            </div>
        </a>

    </div>
        
    <div style="margin-top: 10px" class="d-flex">
        <button style="margin-left: auto" class="btn btn-primary" ng-disabled="Page == 1" ng-click="ChangePage(false)">Prev</button>
        <button style="margin-left: 10px" class="btn btn-primary" ng-disabled="Page == AllPages || Page > AllPages" ng-click="ChangePage(true)">Next</button>
    </div>

</div>

@section scripts
{
    
    <script>
        var app = angular.module('myApp', []);
        app.controller('myCtrl', function ($scope, $http) {

            $scope.Page = 1;
            $scope.AllPages = 0;
            $scope.List = null;

            $http.get("/Movie/GetMovies", { params: { page: $scope.Page }})
                    .then(function (response) {
                        $scope.List = response.data.list;
                        $scope.AllPages = response.data.pages; 
                    }, function(response) {
                      alert("error");
                    });

            $scope.ChangePage = function (next = true) {
                let numberPage = $scope.Page;
                if (next)
                    numberPage++;
                else
                    numberPage--;

                $http.get("/Movie/GetMovies", { params: { page: numberPage }})
                    .then(function (response) {
                        $scope.List = response.data.list;
                        $scope.AllPages = response.data.pages; 
                        $scope.Page = numberPage;
                    }, function(response) {
                      alert("error");
                    });
            };

        });

    </script>
}

Views/Movie/AddMovie.cshtml
@{
    ViewData["Title"] = "Add Movie";
}

<div ng-app="myApp" ng-cloak ng-controller="myCtrl">
    
    <h3>Add new Movie</h3>

    <div class="card-body">
        <table class="table">

            <tr class="d-flex">
                <th class="col-md-2">
                    Name
                </th>
                <td class="col-md-10">
                    <input class="form-control input-sm" ng-model="NewMovie.Name" />
                </td>
            </tr>

            <tr class="d-flex">
                <th class="col-md-2">
                    Description
                </th>
                <td class="col-md-10">
                    <textarea class="form-control input-sm" ng-model="NewMovie.Desc">
                    </textarea>
                </td>
            </tr>

            <tr class="d-flex">
                <th class="col-md-2">
                    Producer
                </th>
                <td class="col-md-10">
                    <input class="form-control input-sm" ng-model="NewMovie.Producer" />
                </td>
            </tr>

            <tr class="d-flex">
                <th class="col-md-2">
                    Year
                </th>
                <td class="col-md-10">
                    <input type="number" class="form-control input-sm" ng-model="NewMovie.Year" />
                </td>
            </tr>

        </table>
        <div class="d-flex">
            <button style="margin-left: auto" class="btn btn-primary" ng-disabled="!NewMovie.Name" ng-click="Add()">Add</button>
        </div>
        
    </div>

</div>

@section scripts
{

    <script>
        var app = angular.module('myApp', []);
        app.controller('myCtrl', function ($scope, $http) {

            $scope.NewMovie = {
                Name: "",
                Desc: "",
                Producer: "",
                Year: null
            };

            $scope.Add = function () {
                
                $http.post("/Movie/AddMovie", $scope.NewMovie)
                    .then(function (response) {
                        document.location.href = response.data;
                    }, function(response) {
                      alert("error");
                    });
            };

        });

    </script>
}

Views/Movie/EditMovie.cshtml
@{
    ViewData["Title"] = "Edit Movie";
}

<div ng-app="myApp" ng-cloak ng-controller="myCtrl">

    <div class="card card-body ">

        <div class="d-flex flex-row">
            <div class="d-flex flex-column">
                <div style="height: 200px">
                    <img ng-if="Movie.posterUrl || Movie.posterUrl.length > 0" src="{{Movie.posterUrl}}" style="height: 100%;" />
                    <img ng-if="!Movie.posterUrl || !Movie.posterUrl.length > 0" src="~/empty_poster.png" style="height: 100%;" />
                </div>

                <input type="file"
                       accept="image/*,image/jpeg"
                       onchange="angular.element(this).scope().Upload(this)"
                       name="uploadedFile"
                       style="margin-top: 10px" /><br>
            </div>

            <div class="d-flex flex-column" style="flex: 1 1 0%; margin-left: 10px">
                <span>Name: </span> <input ng-model="Movie.name"></input>
                <span>Producer: </span> <input ng-model="Movie.producer"></input>
                <span>Year: </span> <input type="number" ng-model="Movie.year"></input>
                <br /><br />
                <h6>Description:</h6>
                <textarea style="max-width: 500px" ng-model="Movie.desc"></textarea>
            </div>


        </div>

        <button style="margin-left: auto; margin-top: 10px; max-height: 38px;"
                class="btn btn-primary"
                ng-click="Save()">
            Save
        </button>

    </div>

</div>

@section scripts
{

    <script>
        var app = angular.module('myApp', ['ngFileUpload']);
        app.controller('myCtrl', function ($scope, $http, Upload) {

            $scope.Movie = @Html.Raw(Json.Serialize(Model));

            $scope.Save = function () {
                $http.post("/Movie/SaveMovie", $scope.Movie)
                    .then(function (response) {
                        document.location.href = response.data;
                    }, function (response) {
                        alert("error");
                    });
            };

            $scope.Upload = function (element) {
                Upload
                    .upload({
                        url: '/Movie/AddFile',
                        data: $scope.Movie.id,
                        file: element.files[0]
                    })
                    .then(function (response) {
                        window.location.reload();
                    }, function (response) {
                        alert(response.data);
                    });

            };
        });
    </script>
}

Views/Movie/Index.cshtml
@{
    ViewData["Title"] = "Movie";
}

<div ng-app="myApp" ng-cloak ng-controller="myCtrl">

    <div class="card card-body ">

        <div class="d-flex flex-row">
            <div style="height: 200px">
                <img ng-if="Movie.posterUrl || Movie.posterUrl.length > 0" src="{{Movie.posterUrl}}" style="height: 100%;" />
                <img ng-if="!Movie.posterUrl || !Movie.posterUrl.length > 0" src="~/empty_poster.png" style="height: 100%;" />
            </div>

            <div class="d-flex flex-column " style="margin-left: 10px">
                <h5>{{Movie.name}}</h5>

                <span>Producer: {{Movie.producer}}</span>
                <span>Year: {{Movie.year}}</span>
                <br /><br />
                <h6>Description:</h6>
                <div style="white-space: pre-wrap">{{Movie.desc}}</div>
            </div>

            @if (Model.User == User.Identity.Name)
            {
                <a style="margin-left: auto; max-height: 38px"
                   class="btn btn-primary"
                   href='~/Movie/EditMovie/{{Movie.id}}'>
                    Edit
                </a>
            }

        </div>

    </div>

</div>

@section scripts
{

    <script>
        var app = angular.module('myApp', []);
        app.controller('myCtrl', function ($scope, $http) {

            $scope.Movie = @Html.Raw(Json.Serialize(Model));

        });

    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestTaskEducationERP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestTaskEducationERP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TestTaskEducationERP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/js/ng-file-upload-all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>